# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edf63627e461cd6867a21f1b7955430da34bcaa20667a63015203d8d8e16b2b56f98b0992661fa5dac63c064c4ebda47a14d0cc6d179ec931865e6075fc14fdb

test:
  secret_key_base: fc91fd9dcf75b912aec19ff14ab071110e3fe5e2f9a2dadd5f25a2acca18ebe635532fe0cfc5a8a8e19740e60bb2a36bc46397c66779bc22af46e5f1257100bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
